services:
  app:  # Nombre del servicio
    build: .  # Construye la imagen usando el Dockerfile en el directorio actual
    ports:
      - "8000:8000"  # Mapea el puerto 8000 del contenedor al puerto 8000 de tu m√°quina
    volumes:
      - .:/app  # Monta tu carpeta de proyecto en el contenedor para reflejar cambios en tiempo real
    environment:
      - PYTHONUNBUFFERED=1  # Asegura que la salida del log sea en tiempo real
      - PYTHONPATH=/app  # Establece `/app` como el directorio de Python
    working_dir: /app  # Establece el directorio de trabajo dentro del contenedor
